# Generated by Django 5.0.6 on 2024-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='conference_logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='logo',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
